/* Phase B: generate a .docx from rich HTML using the clone's exact export
   pipeline (html-to-docx), for real Word to open and read back. */
const htmlToDocx = require('html-to-docx');
const fs = require('fs/promises');
const out = process.argv[2] || '/mnt/c/Users/Public/wcprobe/ref_from_clone.docx';

const body = `
<h1 class="doc-title">Clone Export</h1>
<p class="doc-subtitle">Generated by the clone for round-trip testing</p>
<h1>Formatting</h1>
<p>This has <b>bold</b>, <i>italic</i>, <u>underline</u>, and <span style="color:#FF0000">red</span> text.</p>
<h2>Bulleted List</h2><ul><li>One</li><li>Two</li><li>Three</li></ul>
<h2>Numbered List</h2><ol><li>Alpha</li><li>Beta</li></ol>
<h2>Table</h2><table><tbody><tr><td>Region</td><td>Q1</td><td>Q2</td></tr><tr><td>North</td><td>120</td><td>135</td></tr></tbody></table>
<h2>Hyperlink</h2><p>Visit <a href="https://example.com">example.com</a> for more.</p>`;

(async () => {
  const full = `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body>${body}</body></html>`;
  const buf = await htmlToDocx(full, null, { font: 'Aptos', fontSize: 24, margins: { top: 1440, right: 1440, bottom: 1440, left: 1440, header: 720, footer: 720, gutter: 0 }, table: { row: { cantSplit: true } } });
  await fs.writeFile(out, buf);
  const st = await fs.stat(out);
  console.log('WROTE ' + out + ' (' + st.size + ' bytes)');
})().catch((e) => { console.error('ERR', e); process.exit(1); });
