const fs=require('fs'), path=require('path');
const map=require('./icon-map.json');
const DIR=path.join(__dirname,'..','node_modules','@fluentui/svg-icons/icons');
// Append "!filled" to an icon-map value to PREFER the heavier filled variant (for sparse outline glyphs that read
// too light next to the denser ribbon icons — e.g. Editing's search/replace/select). Default order = regular-first.
function load(name, preferFilled){
  const order = preferFilled
    ? [name+'_24_filled', name+'_20_filled', name+'_28_filled', name+'_24_regular', name+'_20_regular']
    : [name+'_24_regular', name+'_20_regular', name+'_24_filled', name+'_28_regular', name+'_16_regular'];
  for(const v of order){ const p=path.join(DIR,v+'.svg'); if(fs.existsSync(p)) return fs.readFileSync(p,'utf8'); }
  return null;
}
function inner(svg){ const m=svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/i); let b=m?m[1]:svg; b=b.replace(/fill="#[0-9A-Fa-f]{3,8}"/g,'fill="currentColor"').replace(/\sfill="none"/g,''); return b.trim(); }
const out={}, missing=[];
for(const cmd in map){ let name=map[cmd]; let preferFilled=false; if(typeof name==='string' && name.endsWith('!filled')){ name=name.slice(0,-7); preferFilled=true; } const svg=load(name, preferFilled); if(svg) out[cmd]=inner(svg); else missing.push(cmd+' -> '+map[cmd]); }
fs.writeFileSync(path.join(__dirname,'..','src/renderer/public/js/icons-fluent.js'),'/* AUTO-GENERATED by scripts/gen-icons.js from @fluentui/svg-icons (MIT). */\nwindow.WC=window.WC||{};\nwindow.WC.FLUENT='+JSON.stringify(out)+';\n');
console.log('generated icons-fluent.js:', Object.keys(out).length, 'icons | missing:', missing.length);
if(missing.length) console.log('MISSING:\n'+missing.join('\n'));
