// Regenerate the base64-inlined fixture module. Run: node scripts/gen-fixture.js
const fs = require('fs');
const b64 = fs.readFileSync('tests/fixtures/basic-list.docx').toString('base64');
fs.writeFileSync('src/renderer/core/generated/basic-list.docx.b64.ts',
  '// AUTO-GENERATED by scripts/gen-fixture.js — do not edit.\nexport default ' + JSON.stringify(b64) + '\n');
console.log('wrote basic-list.docx.b64.ts (' + b64.length + ' base64 chars)');
