// Regenerate base64-inlined fixture modules.
// Usage (no args — original behaviour):
//   node scripts/gen-fixture.js
// Usage (explicit in/out):
//   node scripts/gen-fixture.js <input.docx> <output.b64.ts> [exportName]
//   exportName: 'default' (default) or a named identifier
const fs = require('fs');
const path = require('path');

const [,, inArg, outArg, exportArg] = process.argv;

if ((inArg && !outArg) || (!inArg && outArg)) {
  console.error('Usage: node scripts/gen-fixture.js <in.docx> <out.b64.ts> [exportName]');
  process.exit(1);
}

if (inArg && outArg) {
  // Parameterised mode
  const exportName = exportArg || 'default';
  const b64 = fs.readFileSync(inArg).toString('base64');
  const relIn = path.relative(process.cwd(), inArg);
  const relOut = path.relative(process.cwd(), outArg);
  const exportLine = exportName === 'default'
    ? 'export default ' + JSON.stringify(b64)
    : 'export const ' + exportName + ' =\n  ' + JSON.stringify(b64);
  const regenCmd = 'node scripts/gen-fixture.js ' + relIn + ' ' + relOut + (exportArg ? ' ' + exportArg : '');
  fs.writeFileSync(outArg,
    '// AUTO-GENERATED from ' + relIn + ' — do not hand-edit.\n' +
    '// Regenerate: ' + regenCmd + '\n' +
    exportLine + '\n');
  console.log('wrote ' + outArg + ' (' + b64.length + ' base64 chars)');
} else {
  // Original no-arg behaviour (basic-list fixture)
  const b64 = fs.readFileSync('tests/fixtures/basic-list.docx').toString('base64');
  fs.writeFileSync('src/renderer/core/generated/basic-list.docx.b64.ts',
    '// AUTO-GENERATED by scripts/gen-fixture.js — do not hand-edit.\n' +
    '// Regenerate: node scripts/gen-fixture.js\n' +
    'export default ' + JSON.stringify(b64) + '\n');
  console.log('wrote basic-list.docx.b64.ts (' + b64.length + ' base64 chars)');
}
